[build]
  functions = "functions"

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true